### ISSUE TITLE
Bug while running python -m solidspy

### ISSUE THREAD

**Issue by meldiwin** [AppliedMechanics-EAFIT/SolidsPy#18]
Enter folder (empty for the current one): 
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/usr/local/lib/python2.7/dist-packages/solidspy/__main__.py", line 5, in <module>
    solids_GUI()
  File "/usr/local/lib/python2.7/dist-packages/solidspy/solids_GUI.py", line 63, in solids_GUI
    nodes, mats, elements, loads = pre.readin(folder=folder)
  File "/usr/local/lib/python2.7/dist-packages/solidspy/preprocesor.py", line 17, in readin
    nodes = np.loadtxt(folder + 'nodes.txt', ndmin=2)
  File "/home/meldiwin/.local/lib/python2.7/site-packages/numpy/lib/npyio.py", line 926, in loadtxt
    fh = np.lib._datasource.open(fname, 'rt', encoding=encoding)
  File "/home/meldiwin/.local/lib/python2.7/site-packages/numpy/lib/_datasource.py", line 262, in open
    return ds.open(path, mode, encoding=encoding, newline=newline)
  File "/home/meldiwin/.local/lib/python2.7/site-packages/numpy/lib/_datasource.py", line 618, in open
    raise IOError("%s not found." % path)
IOError: nodes.txt not found.

**Comment by nicoguaro** [comment]
We need some more information regarding your installation of Python and SolidsPy. Did you installed using Anaconda? Are you using Linux?

**Comment by meldiwin** [comment]
I have used Linux,  I used this simple code, and it gives the error that I have mentioned.
`import matplotlib.pyplot as plt  # load matplotlib
from solidspy import solids_GUI  # import our package
disp = solids_GUI()  # run the Finite Element Analysis
plt.show()    # plot contour`

**Comment by meldiwin** [comment]
`Enter folder (empty for the current one): 
Traceback (most recent call last):
  File "simple.py", line 3, in <module>
    disp = solids_GUI()  # run the Finite Element Analysis
  File "/home/meldiwin/SolidsPy/solidspy/solids_GUI.py", line 63, in solids_GUI
    nodes, mats, elements, loads = pre.readin(folder=folder)
  File "/home/meldiwin/SolidsPy/solidspy/preprocesor.py", line 17, in readin
    nodes = np.loadtxt(folder + 'nodes.txt', ndmin=2)
  File "/usr/lib/python2.7/dist-packages/numpy/lib/npyio.py", line 896, in loadtxt
    fh = iter(open(fname, 'U'))
IOError: [Errno 2] No such file or directory: 'nodes.txt'`
