### ISSUE TITLE
ERROR in "from solidspy.solids_GUI import solids_auto"

### ISSUE THREAD

**Issue by koz7** [AppliedMechanics-EAFIT/SolidsPy#28]
Thank you providing a great project!
Here is an error when I try to import solids_auto:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/user/Library/Python/2.7/lib/python/site-packages/solidspy/__init__.py", line 3, in <module>
    from solidspy.solids_GUI import solids_GUI
  File "/Users/user/Library/Python/2.7/lib/python/site-packages/solidspy/solids_GUI.py", line 26, in <module>
    import solidspy.postprocesor as pos
  File "/Users/user/Library/Python/2.7/lib/python/site-packages/solidspy/postprocesor.py", line 26, in <module>
    plt.rcParams["axes.spines.right"] = False
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/matplotlib/__init__.py", line 794, in __setitem__
    See rcParams.keys() for a list of valid parameters.' % (key,))
KeyError: 'axes.spines.right is not a valid rc parameter.See rcParams.keys() for a list of valid parameters.'

How can I solve this issue?
Thank you in advance:)

**Comment by nicoguaro** [comment]
It seems that you are using Python 2.7. But we dropped it last year with the end of support.

**Comment by koz7** [comment]
Thank you @nicoguaro for your reply.
I changed to Python3.7.6, but I have another error here:
libc++abi.dylib: terminating with uncaught exception of type NSException

Is there any other problem in my environment?

Thank you for your support.

**Comment by nicoguaro** [comment]
I just realized that you seem to be using the development version. What was your setup process?

**Comment by koz7** [comment]
Thank you @nicoguaro for your reply.
I followed the instruction and run
pip install solidspy
pip install easygui
pip install meshio
My environment seems to be anaconda.

**Comment by nicoguaro** [comment]
@koz7, I think I know what the problem is. You are installing the stable version (1.0.16) but the readme in GitHub is presenting an example for the developing version (2.x). I would suggest that you check the official documentation

https://solidspy.readthedocs.io/en/latest/readme.html

Try the steps there and let me know if it works.
